version: '3.7'

services:
  iss_aprs_tracker:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      iss_aprs_tracker_db:
        condition: service_started
    environment:
        CALLSIGN: ${CALLSIGN:-N0SIGN}
        DB_HOST: ${DB_HOST:-iss_aprs_tracker_db}
        DB_PORT: ${DB_PORT:-3306}
        DB_SOCKET: 'false'
        DB_USERNAME: ${DB_USERNAME:-user}
        DB_PASSWORD: ${DB_PASSWORD:-changeme}
        DB_DATABASE: ${DB_DATABASE:-iss_tracker}
        LOG_LEVEL: ${LOG_LEVEL:-WARNING}
  iss_aprs_tracker_db:
    image: mysql:8
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme}
      MYSQL_DATABASE: ${DB_DATABASE:-iss_tracker}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
    db_data: